import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  myBookSidebar: [
    {
      type: 'category',
      label: 'Module-0',
      items: [
        {
          type: 'autogenerated',
          dirName: '0-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module-1',
      items: [
        {
          type: 'autogenerated',
          dirName: '1-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module-2',
      items: [
        {
          type: 'autogenerated',
          dirName: '2-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module-3',
      items: [
        {
          type: 'autogenerated',
          dirName: '3-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module-4',
      items: [
        {
          type: 'autogenerated',
          dirName: '4-capstone',
        },
      ],
    },
  ],

};

export default sidebars;
